# frozen_string_literal: true

require 'rails_helper'

# Grid item notes are jsonb and rendered as nested JSON. Most responses are
# generated by Blueprinter with Oj (no depth limit), but endpoints that render
# a Ruby hash go through Rails' JSON encoder, which in Rails 8.1 enforces a
# 100-level limit on the whole response. Notes at the validator's maximum
# depth must render on both paths, including on substitutes (the deepest
# place they appear).
RSpec.describe 'Rendering deep rich-text notes', type: :request do
  let(:user) { create(:user) }
  let(:headers) do
    token = Doorkeeper::AccessToken.create!(resource_owner_id: user.id, expires_in: 30.days, scopes: 'public')
    { 'Authorization' => "Bearer #{token.token}" }
  end
  let(:party) { create(:party, user: user, visibility: 1) }
  let!(:weapon) { create(:grid_weapon, party: party, position: 0, description: deepest_allowed_note) }

  before do
    substitute = create(:grid_weapon, party: party, position: 1, is_substitute: true, description: deepest_allowed_note)
    Substitution.create!(grid: weapon, substitute_grid: substitute, position: 0)
  end

  def deepest_allowed_note
    node = { 'type' => 'paragraph', 'content' => [] }
    ((RichTextDescriptionValidator::MAX_JSON_DEPTH - 4) / 2).times do
      node = { 'type' => 'blockquote', 'content' => [node] }
    end
    { 'type' => 'doc', 'content' => [node] }
  end

  def expect_notes_rendered
    expect(response).to have_http_status(:ok)
    rendered = response.parsed_body['party']['weapons'].find { |w| w['id'] == weapon.id }
    expect(rendered['description']).to eq(deepest_allowed_note)
    expect(rendered['substitutions'].first['grid_weapon']['description']).to eq(deepest_allowed_note)
  end

  it 'renders through Blueprinter (party show)' do
    get "/api/v1/parties/#{party.shortcode}", headers: headers
    expect_notes_rendered
  end

  it "renders through Rails' JSON encoder (an endpoint that renders a hash)" do
    post "/api/v1/parties/#{party.id}/unlink_collection", headers: headers
    expect_notes_rendered
  end
end
