# frozen_string_literal: true

namespace :granblue do
  desc "Load/upsert conditional weapon skill effects from data/weapon_skill_effects.json"
  task load_weapon_skill_effects: :environment do
    if WeaponSkillEffect.exists? && ENV["SEED"] != "1"
      abort "weapon_skill_effects is not empty — the DB is the source of truth. " \
            "Pass SEED=1 to sync from the JSON snapshot anyway (manually-edited rows are preserved)."
    end

    file = Rails.root.join("data", "weapon_skill_effects.json")
    payload = JSON.parse(File.read(file))
    records = payload.is_a?(Hash) ? payload["effects"] : payload
    puts "Loading #{records.size} weapon skill effects..."

    cols = %w[series value value_unit per_copy_cap total_cap shared_cap_group
              cap_formula count_basis count_cap condition target_instance depends_on
              aura_boostable seraphic_affected stacking applies_to battle_interaction notes]

    created = 0
    updated = 0
    skipped_manual = 0
    records.each do |r|
      effect = WeaponSkillEffect.find_or_initialize_by(
        modifier: r["modifier"], boost_type: r["boost_type"], scaling_kind: r["scaling_kind"],
        key_slug: r["key_slug"], condition: r["condition"] || {}
      )
      if effect.persisted? && effect.manually_edited_at.present?
        skipped_manual += 1
        next
      end
      created += 1 if effect.new_record?
      updated += 1 if effect.persisted?
      cols.each do |c|
        next unless r.key?(c)
        effect[c] = r[c]
      end
      # apply schema defaults for omitted columns
      effect.condition ||= {}
      effect.depends_on ||= []
      effect.save!
    end
    puts "Done. created=#{created} updated=#{updated} skipped_manual=#{skipped_manual} total=#{WeaponSkillEffect.count}"
  end

  desc "Export weapon_skill_effects from the DB -> data/weapon_skill_effects.json (committable snapshot)"
  task export_weapon_skill_effects: :environment do
    cols = %w[modifier boost_type series scaling_kind value value_unit per_copy_cap total_cap
              shared_cap_group cap_formula count_basis count_cap condition target_instance depends_on
              aura_boostable seraphic_affected stacking applies_to battle_interaction notes key_slug frame_rule]
    rows = WeaponSkillEffect.where(weapon_skill_version_id: nil).map do |e|
      cols.each_with_object({}) do |c, out|
        v = e[c]
        next if v.nil? || v == {} || v == []

        out[c] = v.is_a?(BigDecimal) ? v.to_f : v
      end
    end
    rows.sort_by! { |r| [r["modifier"].to_s, r["boost_type"].to_s, r["scaling_kind"].to_s, r["key_slug"].to_s] }
    payload = {
      "_generated" => "Exported from the hensei DB (source of truth) by rake granblue:export_weapon_skill_effects.",
      "effects" => rows
    }
    File.write(Rails.root.join("data", "weapon_skill_effects.json"), "#{JSON.pretty_generate(payload)}\n")
    manual = WeaponSkillEffect.where.not(manually_edited_at: nil).count
    puts "Exported #{rows.size} canonical rows (#{manual} carry manual edits); version-linked rows are regenerated by reparse, not exported."
  end
end
