[phases.setup]
nixPkgs = [
    "imagemagick",
    # For PDF/PS operations
    "ghostscript",
    # For gem compilation
    "pkgconfig",
    # ImageMagick C library
    "libmagickwand",
    # Font configuration
    "fontconfig",
    # A good fallback font
    "dejavu_fonts",
    # Arial-compatible fonts
    "liberation_ttf",
    # Font rendering
    "freetype"
]

[phases.install]
dependsOn = ["setup"]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "bin/rails server"
