default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['PGHOST'] %>
  port: <%= ENV['PGPORT'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  encoding: utf8
  timeout: 5000

production:
  <<: *default
  database: <%= ENV['PGDATABASE'] %>

development:
  <<: *default
  database: hensei_dev

test:
  <<: *default
  database: hensei_test
