default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: hensei_dev
  username: justin
  password:
  encoding: utf8

test:
  <<: *default
  database: hensei_test

production:
  <<: *default
  database: hensei
