module PreviewService
  class Canvas
    PREVIEW_WIDTH: Integer
    PREVIEW_HEIGHT: Integer
    DEFAULT_BACKGROUND_COLOR: String

    def create_blank_canvas: (
        ?width: Integer,
        ?height: Integer,
        ?color: String
      ) -> Tempfile

    def add_text: (
        MiniMagick::Image image,
        String text,
        ?x: Integer,
        ?y: Integer,
        ?size: String,
        ?color: String,
        ?font: String
      ) -> MiniMagick::Image
  end
end
