# frozen_string_literal: true

# weapon_skills becomes slot identity only; all per-tier data (skill, modifier,
# series, size, unlock_level) moves to weapon_skill_versions. The per-weapon
# weapon_skills rows are fully derived from weapons.wiki_raw (regenerated by
# rake granblue:parse_weapon_skills), so existing rows are cleared rather than
# migrated — the old (weapon_granblue_id, position, uncap_level) rows would
# collide on the new (weapon_granblue_id, position) unique index otherwise.
class SlimDownWeaponSkills < ActiveRecord::Migration[8.0]
  def up
    # Derived data — safe to clear and re-parse. Removes pre-existing duplicate
    # (weapon_granblue_id, position) rows so the new unique index can be created.
    execute('DELETE FROM weapon_skills')

    remove_index :weapon_skills, name: 'index_weapon_skills_on_weapon_position_uncap'
    remove_index :weapon_skills, name: 'index_weapon_skills_on_skill_series'
    remove_index :weapon_skills, name: 'index_weapon_skills_on_skill_id'

    remove_column :weapon_skills, :skill_id
    remove_column :weapon_skills, :skill_modifier
    remove_column :weapon_skills, :skill_series
    remove_column :weapon_skills, :skill_size
    remove_column :weapon_skills, :unlock_level
    remove_column :weapon_skills, :uncap_level

    add_index :weapon_skills, %i[weapon_granblue_id position],
              unique: true, name: 'index_weapon_skills_on_weapon_position'
  end

  def down
    remove_index :weapon_skills, name: 'index_weapon_skills_on_weapon_position'

    add_column :weapon_skills, :skill_id, :uuid
    add_column :weapon_skills, :skill_modifier, :string
    add_column :weapon_skills, :skill_series, :string
    add_column :weapon_skills, :skill_size, :string
    add_column :weapon_skills, :unlock_level, :integer
    add_column :weapon_skills, :uncap_level, :integer, null: false, default: 0

    add_index :weapon_skills, :skill_id, name: 'index_weapon_skills_on_skill_id'
    add_index :weapon_skills, :skill_series, name: 'index_weapon_skills_on_skill_series'
    add_index :weapon_skills, %i[weapon_granblue_id position uncap_level],
              unique: true, name: 'index_weapon_skills_on_weapon_position_uncap'
  end
end
