# frozen_string_literal: true

module Granblue
  module Importers
    class ImportError
      attr_reader file_name: String
      attr_reader details: String

      def initialize: (file_name: String, details: String) -> void

      private

      def build_message: () -> String
    end

    def format_attributes: (
        attributes: Hash[Symbol, String | Integer | Float | Boolean | Array[untyped] | nil]
      ) -> String
  end
end
