module Granblue
  module Downloaders
    class DownloadManager
      def self.download_for_object: (
          String type,
          String granblue_id,
          ?test_mode: bool,
          ?verbose: bool,
          ?storage: Symbol
        ) -> void

      private
    end
  end
end
