module Granblue
  module Downloaders
    class SummonDownloader < BaseDownloader
      def download: -> void

      private

      def download_variants: (Summon summon) -> void

      def download_variant: (String variant_id) -> void

      def build_variant_url: (String variant_id, String size) -> String

      def object_type: -> String

      def base_url: -> String

      def directory_for_size: (String size) -> String

      private

      @id: String
      @base_url: String
      @test_mode: bool
      @verbose: bool
      @storage: Symbol
      @aws_service: AwsService
    end
  end
end
